### ISSUE TITLE
『方舟素材』命令报错

### ISSUE THREAD

**Issue by WindStill** [xulai1001/akgacha#4]
![image](https://user-images.githubusercontent.com/958456/176344433-f14a6ac6-8fa9-4ec0-bee4-19760e291d80.png)

PS：不要在意我报错的『行数』，我前面加了点内容

**Comment by xulai1001** [comment]
报错是说Service名字出错

github原版代码里，init_browser实现如下：

>def init_browser():

>    global driver1

>    logger.info('初始化Selenium ...')

>    driver1 = webdriver.Chrome(chrome_options=options)

并无此行: service_object= Service(binary_path)
请检查您自行添加的代码

**Comment by WindStill** [comment]
> 报错是说Service名字出错
> 
> github原版代码里，init_browser实现如下：
> 
> > def init_browser():
> 
> > global driver1
> 
> > logger.info('初始化Selenium ...')
> 
> > driver1 = webdriver.Chrome(chrome_options=options)
> 
> 并无此行: service_object= Service(binary_path) 请检查您自行添加的代码

确实，我的问题。我用的docker版本的HoshinoBot，不好安装chromedriver，所以安装了chromedriver_py。引入的Service跟HoshinoBot的Service冲突了。

不过还是没解决chromedriver的问题，docker里好像缺少chromedriver的系统依赖。不知道大佬有没有docker中安装试用chromedriver的方法

**Comment by xulai1001** [comment]
就嗯装。。
自用的容器里为了装chromedriver和chromium，把整套gui依赖都装进去了……
如果不使用在线获取的话，可以看看以前的版本里可能有发送本地（预下载）素材一图流图片的代码

**Comment by WindStill** [comment]
> 就嗯装。。 自用的容器里为了装chromedriver和chromium，把整套gui依赖都装进去了…… 如果不使用在线获取的话，可以看看以前的版本里可能有发送本地（预下载）素材一图流图片的代码

嗯。改成发送本地图片了
