### ISSUE TITLE
不能切换到限定卡池

### ISSUE THREAD

**Issue by thankU-ubi** [xulai1001/akgacha#5]
获取卡池信息时没有限定卡池，比如水陈和R6干员，手动输入卡池名称也没有找到。还有要是十连的图片能换成大图就好了，多张half头像容易被风控

**Comment by xulai1001** [comment]
漏卡池可能是最近的commits导致的，这部分需要修正。

十连的图片是bot拼接之后发送的单张图片，风控可能是因为单条消息过长，可以参考 #3 。
事实上发其他图片和链接也容易导致风控，我自己使用的bot为了不被封号基本放弃了所有发图功能

**Comment by xulai1001** [comment]
卡池自动更新模块会读取PRTS的卡池信息页面进行识别，但是“[【跨年欢庆寻访】跨年欢庆·回首](https://prts.wiki/w/%E5%9B%9E%E9%A6%96)”这个卡池信息里包含了嵌套表格，导致正则匹配出现问题。
![QQ截图20220703163449](https://user-images.githubusercontent.com/2126803/177031906-37d12533-96a7-459f-9f16-b5ae318fda95.jpg)

设法绕过这个池子

**Comment by xulai1001** [comment]
37f5b47
过滤了嵌套表格，问题解决
