### ISSUE TITLE
启动报错，什么原因怎么解决

### ISSUE THREAD

**Issue by liuzj288** [xulai1001/akgacha#6]
![image](https://user-images.githubusercontent.com/13833404/176979492-5769b74d-aa58-428d-94fd-8b0bc2086c70.png)
![image](https://user-images.githubusercontent.com/13833404/176979521-6571d021-0024-4326-9e85-35407a90ca62.png)
![image](https://user-images.githubusercontent.com/13833404/176979564-a75b996e-cf97-495e-8f3b-999f725fb0af.png)

**Comment by xulai1001** [comment]
和Hoshino版本有关
尝试把from hoshino import MessageSegment 改为from hoshino.typing

另外本插件没有在windows下进行测试

**Comment by xulai1001** [comment]
https://github.com/xulai1001/akgacha/commit/473cdcbf2e009f9cfd69523cb8718ef9c9d3fd48
