### ISSUE TITLE
国内无法访问raw.githubusercontent.com导致报错

### ISSUE THREAD

**Issue by SparkChen927** [xulai1001/akgacha#9]
执行“***更新方舟基础数据***”时报错
`更新失败……SOCKSHTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Kengxxiao/ArknightsGameData/master/zh_CN/gamedata/excel/character_table.json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000018502C92AF0>: Failed to establish a new connection: SOCKS5 proxy server sent invalid data'))`

在*prtsres.py*的*update_chara_db*函数中的网址挂代理*ghproxy.com*可以解决

`try:
        res = await aiorequests.get("https://ghproxy.com/https://raw.githubusercontent.com/Kengxxiao/ArknightsGameData/master/zh_CN/gamedata/excel/character_table.json", timeout=20)
    except:
        res = await aiorequests.get("https://ghproxy.com/https://raw.githubusercontent.com/Kengxxiao/ArknightsGameData/master/zh_CN/gamedata/excel/character_table.json", proxies=proxies, timeout=20)`

**Comment by xulai1001** [comment]
确实要挂代理而且需要修改这里，我更新的时候得在readme里额外说明一下。
